# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.ambr$'  # Exclude syrupy snapshot files
      - id: end-of-file-fixer
        exclude: '^uv\.lock$'
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files
        exclude: '^uv\.lock|examples/example-dagster/uv\.lock$'
  - repo: local
    hooks:
    - id: ruff-check
      name: Ruff Check
      entry: uv run ruff check --fix
      language: system
      pass_filenames: false
    - id: ruff-format
      name: Ruff Format
      entry: uv run ruff format
      language: system
      pass_filenames: false
    - id: dprint-format
      name: Dprint Format
      entry: uv run dprint fmt
      language: system
      pass_filenames: false
    - id: deptry
      name: Deptry
      entry: uv run deptry src
      language: system
      pass_filenames: false
    - id: typecheck
      name: Typecheck
      entry: uv run ty check
      language: system
      pass_filenames: false
    - id: build-docs
      name: Build Docs
      entry: uv run --group docs mkdocs build --strict
      language: system
      pass_filenames: false
      files: ^(src/|docs/|pyproject\.toml|uv\.lock|mkdocs\.yml|\.pre-commit-config\.yaml)
    - id: test-docs
      name: Test Docs Codeblocks
      entry: uv run pytest ./docs
      language: system
      pass_filenames: false
      files: ^(src/|docs/|pyproject\.toml|uv\.lock|mkdocs\.yml|\.pre-commit-config\.yaml)
